# Generated by Django 3.2.18 on 2023-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description_short', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта')),
            ],
        ),
    ]
