# Generated by Django 3.2.18 on 2023-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sequence_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер изображения'),
        ),
    ]
