# Generated by Django 4.2 on 2023-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_sequence_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AlterField(
            model_name='image',
            name='sequence_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядковый номер изображения'),
        ),
    ]
